feat(customer-service): CRUD customer service
insightlearning/plata-bank pull request #7
Opened 2019-10-30 01:53 UTC by diegolucasilva

2019-10-30 02:59 UTC, KaiqueLeao commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/mapper/CustomerMapper.java
> +    AddressDto toAddressDto(Address address);
Será que faz sentido termos no CustomerMapper também os objetos aninhados?
Acredito que quando vc faz o mapper do Customer pro CustomerDTO, as classes aninhadas são tratadas junto.

2019-10-30 13:30 UTC, diegolucasilva commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/mapper/CustomerMapper.java
> +    AddressDto toAddressDto(Address address);
Caso os métodos de conversão das classes aninhadas não sejam declaradas, as entities serão usadas diretamente. É possível ver isso olhando o .class gerado

2019-11-01 02:11 UTC, padovese requested changes

2019-11-01 02:11 UTC, padovese commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/controller/CustomerController.java
> +    @ResponseBody
Isso me parece redundante, uma vez que a anotação @RestController é uma anotação composta pela @Controller + @ResponseBody. Algum motivo em específico?

2019-11-01 02:11 UTC, padovese commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/domain/Customer.java
> +    @OneToOne(cascade=CascadeType.ALL)
Dúvida: essa abordagem gera valor de ID pras sub-classes? Pois foi retirado o @GeneratedValue

2019-11-01 02:11 UTC, padovese commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/service/CustomerService.java
> +        return Optional.ofNullable(customerRepository.save(customer));
Acho que se existe alguma validação para ver se o customer é nulo, deve ser feita antes de persistir ele, não depois. Nesse caso, mesmo se voltar nulo não vai ter diferenca esse optional.
ps: não sei se o mapper faz alguma validação.

2019-11-02 02:53 UTC, diegolucasilva commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/controller/CustomerController.java
> +    @ResponseBody
Não precisa mesmo. retirado.

2019-11-02 02:54 UTC, diegolucasilva commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/domain/Customer.java
> +    @OneToOne(cascade=CascadeType.ALL)
Gera sim.

2019-11-04 02:48 UTC, padovese submitted a review, later dismissed

2019-11-05 01:48 UTC, KaiqueLeao requested changes

2019-11-05 01:48 UTC, KaiqueLeao commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/controller/CustomerController.java
> +    public List<CustomerDto> findAll(){
Por se tratar de uma abreviação de data transfer object, acredito que o nome do dto ficaria melhor com DTO em caixa alta.

2019-11-05 01:48 UTC, KaiqueLeao commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/mapper/CustomerMapper.java
> +    Address toAddress(AddressDto addressDto);
Mesma sugestão de padronização citada no comentário acima.

2019-11-05 01:48 UTC, KaiqueLeao commented on customer-service/src/test/java/com/insight/learning/platabank/customerservice/controller/CustomerControllerTest.java
> +    private static String mapToJson(Object obj) throws JsonProcessingException {
Classe de teste com muita responsabilidade, conforme conversamos, talvez fosse necessário separar os métodos de criação de objeto em uma outra classe.

2019-11-06 01:31 UTC, diegolucasilva commented on customer-service/src/main/java/com/insight/learning/platabank/customerservice/controller/CustomerController.java
> +    public List<CustomerDto> findAll(){
Make sense buddy. Renomeados.

2019-11-06 01:38 UTC, diegolucasilva commented on customer-service/src/test/java/com/insight/learning/platabank/customerservice/controller/CustomerControllerTest.java
> +    private static String mapToJson(Object obj) throws JsonProcessingException {
Remove a responsabilidade de transformação de Json para outra classe

2019-11-07 03:28 UTC, KaiqueLeao approved these changes

2019-11-13 00:14 UTC, merged