Feature/transference service
insightlearning/plata-bank pull request #8
Opened 2019-11-10 00:16 UTC by KaiqueLeao

Ainda não esta persistindo a transferência mas estou abrindo o MR pra não acumular tanta coisa pra code review.

2019-11-10 23:43 UTC, diegolucasilva requested changes

2019-11-10 23:43 UTC, diegolucasilva commented on transference-service/build.gradle
> -	implementation 'org.springframework.boot:spring-boot-starter-web'
Acho que você não está usando essa deb, está?

2019-11-10 23:43 UTC, diegolucasilva commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Account.java
> +    private Integer account;
o nome da entidade é account, não é melhor esse atributo ter o nome de id?

2019-11-10 23:43 UTC, diegolucasilva commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Bank.java
> +public class Bank {
O prefixo bank no nome dos atributos é redundante.

2019-11-10 23:43 UTC, diegolucasilva commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Payee.java
> +    private Integer account;
Um favorecido deveria agregar a entidade account?

2019-11-10 23:43 UTC, diegolucasilva commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Transference.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Tem algum motivo pra usar GenerationType.IDENTITY? 
O default(não precisa colocar nada ou poem GenerationType.AUTO) deixa o provedor de persistência escolher a estratégia mais adequada de acordo com o banco de dados. O IDENTITY não é suportado em alguns bancos.

2019-11-10 23:43 UTC, diegolucasilva commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Transference.java
> +    @Setter(AccessLevel.NONE)
boa

2019-11-12 00:00 UTC, KaiqueLeao commented on transference-service/build.gradle
> -	implementation 'org.springframework.boot:spring-boot-starter-web'
Não estava utilizando a dependência do netflix ribbon, removi a mesma.

2019-11-12 00:25 UTC, KaiqueLeao reviewed
Correções aplicadas conforme solicitado.

2019-11-12 00:25 UTC, KaiqueLeao commented on transference-service/build.gradle
> -	implementation 'org.springframework.boot:spring-boot-starter-web'
> Acho que você não está usando essa deb, está?

Não estava utilizando a dependência do netflix ribbon, removi a mesma.

2019-11-12 00:25 UTC, KaiqueLeao commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Account.java
> +    private Integer account;
> o nome da entidade é account, não é melhor esse atributo ter o nome de id?

Realmente, nem me toquei que coloquei esse nome kkk
Correção aplicada.

2019-11-12 00:25 UTC, KaiqueLeao commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Bank.java
> +public class Bank {
> O prefixo bank no nome dos atributos é redundante.

Mais um vacilo kkkk, correção aplicada.

2019-11-12 00:25 UTC, KaiqueLeao commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Transference.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
> Tem algum motivo pra usar GenerationType.IDENTITY?
> O default(não precisa colocar nada ou poem GenerationType.AUTO) deixa o provedor de persistência escolher a estratégia mais adequada de acordo com o banco de dados. O IDENTITY não é suportado em alguns bancos.

Boa observação, coloquei pelo hábito de sempre ter colocado quando usava JPA
Correção aplicada.

2019-11-12 00:25 UTC, KaiqueLeao commented on transference-service/src/main/java/com/insight/learning/platabank/transferenceservice/domain/Payee.java
> +    private Integer account;
Sim sim, faz sentido mano, correção aplicada.

2019-11-12 00:35 UTC, diegolucasilva commented on transference-service/build.gradle
> -	implementation 'org.springframework.boot:spring-boot-starter-hateoas'
eu tinha falado sobre o starter-web e não do hateoas kk. Mas não deve estar usando ainda certo?

2019-11-12 00:41 UTC, diegolucasilva approved these changes

2019-11-12 00:47 UTC, merged